### ISSUE TITLE
general question regarding very high similary scores in aggregation methods

### ISSUE THREAD

**Issue by wjtan99** [PyRetri/PyRetri#4]
Thanks a lot for your great great work putting so many nice stuffs together.
  
This question is not related to your work, but I think maybe you can shed me some light.  

All aggregation methods except the max pooling gives very high similarity score for two very different images.  This cosine similarity is typically larger than 0.7 or 0.8 with avg pooling, spoc, crow etc.  What do you do with it in image retrieval? I think about mapping the similarity score baco to 0 to 1, like a min-max norm or a hard mapping,  but I am not sure it is the right thing to do.  

Thanks a lot.

**Comment by hby96** [comment]
Hi~

This is an interesting question which I didn't notice before, but I think this may be explained from the perspective of feature norm.

Since the pre-trained network only learned the interface of the classifiers during the training process, and did not constrain the feature norm and the angle between the features, so high similarity score for two very different images is inevitable.

I think constrain the feature norm during training is essential to solve this problem like metric learning methods or feature normalization methods used in face recognition. If you do not want to re-train the model, post-process methods like l2-normalization may be helpful.

Min-max norm may make the similarity score smaller but will not change their relative order, I wonder if it will work.

Hope my answer can help you~

**Comment by wjtan99** [comment]
Thanks for your reply.  Deep metric learning is something worth trying. But most, if not all, papers use pre-trained CNN.  L2 normalized is already used on every aggregation method.  The high similarity score will make the false positive rate hard to control.  Authors of those papers may not try query of an image out of the data set.  Otherwise, the FP rate will be pretty high.   
Min-max does not change the order of similarity scores.  But if we do min-max globally within the whole data set, it may give a good reference for images out of the data set as query.

**Comment by hby96** [comment]
Sounds reasonable. Thanks for your patient explanation :)

**Comment by wjtan99** [comment]
I sent an email to the SPOC authors, and see how they answer.
